package gitlet;

import java.io.File;
import java.io.Serializable;

/**
 * Represents a blob object that stores file content snapshot.
 * Blob ID is generated by SHA-1 hash of file content.
 * Identical content shares the same blob.
 *
 * @author huang.kai
 */
public class Blob implements Serializable {
    /**
     * The content of the file.
     */
    private final byte[] content;

    /**
     * The ID of this blob.
     */
    private final String blobID;

    /**
     * Creates a new Blob with the given content.
     */
    public Blob(byte[] content) {
        this.content = content;
        this.blobID = generateID();
    }

    /**
     * Creates a new Blob with the given file.
     */
    public Blob(File file) {
        this.content = Utils.readContents(file);
        this.blobID = generateID();
    }

    /**
     * Returns the ID of this blob.
     */
    public String getBlobID() {
        return blobID;
    }

    /**
     * Returns the content of this blob.
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * Generates the ID based on content.
     */
    private String generateID() {
        return Utils.sha1((Object) content);
    }
}
